# Generated by Django 4.2.3 on 2023-07-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('places', models.CharField(blank=True, max_length=50)),
                ('information', models.TextField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
